color = input("Enter a color: ")
plural_noun = input("enter a plural noun: ")
celebrity = input("enter a celebrity: ")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love " + celebrity)
