phrase = "Giraffe Academy"
print(phrase)
print(phrase.upper())
print(phrase.lower())
print(phrase.upper().isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("G"))
print(phrase.index("a"))
print(phrase.index("Acad"))
print(phrase.replace("Giraffe", "Elephant"))
print(phrase)
